config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url('admin/', admin.site.urls),
    path('ancillary/', include('impressions.ancillary.urls', namespace='ancillary')),
    path('', include('impressions.core.urls', namespace='core')),
    path('map/', include('impressions.map.urls', namespace='map')),
    path('special/', include('impressions.special.urls', namespace='special')),
    path('stories/', include('impressions.stories.urls', namespace='stories')),
    path('supporting/', include('impressions.supporting.urls', namespace='supporting')),
    path('themes/', include('impressions.themes.urls', namespace='themes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Also ensure static files are served
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

impressions/special/urls.py
from django.urls import path, re_path
from . import views

app_name="special"

urlpatterns = [
    path('feature/', views.FeatureListView.as_view(), name='feature_list'),

    # CBV approach
    # The first part of each name has to match the corresponding
    # name in special.Feature.special_type, e.g. "video"_detail
    # Applies only to the "staring" names, not subsequent slide details

    # ----------- NON-SLIDE FEATURES ---------

    #  ------ VIDEO ---
    path('video/<slug:slug>/', 
        views.FullVideoDetailView.as_view(), name='video_detail'),

    path('ajax/video/<slug:slug>/', 
        views.VideoDetailView.as_view(), name='ajax_video_detail'),

    path('swapfull/video/<slug:slug>/', 
        views.SwapFullVideoDetailView.as_view(), name='swapfull_video_detail'),

    #  ------ VOICE ---
    # Should have been voice, singular, but too hard to change now
    path('voices/<slug:slug>/', 
        views.FullVoiceDetailView.as_view(), name='voices_detail'),

    path('ajax/voices/<slug:slug>/', 
        views.VoiceDetailView.as_view(), name='ajax_voices_detail'),

    path('swapfull/voices/<slug:slug>/', 
        views.SwapFullVoiceDetailView.as_view(), name='swapfull_voices_detail'),

    #  ------ EXPLORE ---
    path('explore/<slug:slug>/', 
        views.FullExploreDetailView.as_view(), name='explore_detail'),

    path('ajax/explore/<slug:slug>/', 
        views.ExploreDetailView.as_view(), name='ajax_explore_detail'),

    path('swapfull/explore/<slug:slug>/', 
        views.SwapFullExploreDetailView.as_view(), name='swapfull_explore_detail'),

    #  ------ DICOVERERS ---
    # Not stand-alone -- only serves voting in Whose Discovery, Chapter 8
    path('discoverers/<slug:slug>/<slide_num>/', 
        views.DiscoverersDetailView.as_view(), name='discoverers_detail'),

    # ----------- SLIDE-BASED FEATURES ---------

    #  ------ THEN AND NOW ---
    path('then/<slug:slug>/', 
        views.FullThenDetailView.as_view(), name='then_detail'),

    path('ajax/then/<slug:slug>/', 
        views.ThenDetailView.as_view(), name='ajax_then_detail'),

    path('swapfull/then/<slug:slug>/', 
        views.SwapFullThenDetailView.as_view(), name='swapfull_then_detail'),

    #  ------ LOOKING ---
    path('looking/<slug:slug>/', 
        views.FullLookingDetailView.as_view(), name='looking_detail'),

    path('ajax/looking/<slug:slug>/', 
        views.LookingDetailView.as_view(), name='ajax_looking_detail'),

    path('swapfull/looking/<slug:slug>/', 
        views.SwapFullLookingDetailView.as_view(), name='swapfull_looking_detail'),


    #  ------ SLIDESHOW ---
    # Zero param must also go to intro. We're dependent on the link_name 
    # which distinguishes full from slim pop, so we can't just use 
    # slideshow_detail (no int param) for the link in nav
    re_path('slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.IntroSlideshowDetailView.as_view(), name='reintro-slideshow_detail'),

    #  with slide number (other than 0)
    path('slideshow/<slug:slug>/<slide_num>/', 
        views.SlideshowDetailView.as_view(), name='slideshow_slide_detail'),

    # default - full (changed Nov 1, 2017)
    path('slideshow/<slug:slug>/', 
        views.IntroFullSlideshowDetailView.as_view(), name='slideshow_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='full_slideshow_re_intro_detail'),

    #  full screen with slide number
    path('full/slideshow/<slug:slug>/<slide_num>/', 
        views.FullSlideshowDetailView.as_view(), name='full_slideshow_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/slideshow/<slug:slug>/', 
        views.IntroSlideshowDetailView.as_view(), name='intro_ajax_slideshow_detail'),

    # the moment when you come from a see also on a person full slim
    # re-use ReIntroFullSlideshowDetailView
    path('swapfull/slideshow/<slug:slug>/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='swapfull_slideshow_detail'),


    #  ------ SOCIETY ---
    # choice for vote
    path('society/choice/<slug:slug>/<slide_num>/<int:choice>)/', 
        views.SocietyChoiceDetailView.as_view(), name='society_choice'),

    # zero version of intro
    re_path('society/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroSocietyDetailView.as_view(), name='society_detail'),

    #  with slide number
    path('society/<slug:slug>/<slide_num>/', 
        views.SocietyDetailView.as_view(), name='society_slide_detail'),

    # default - intro (changed Nov 1, 2017)
    path('society/<slug:slug>/', 
        views.IntroFullSocietyDetailView.as_view(), name='society_detail'),


    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/society/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='full_society_re_intro_detail'),

    #  full screen with slide number
    path('full/society/<slug:slug>/<slide_num>/', 
        views.FullSocietyDetailView.as_view(), name='full_society_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/society/<slug:slug>/', 
        views.IntroSocietyDetailView.as_view(), name='ajax_society_detail'),

    # re-use ReIntroFullSocietyDetailView
    path('swapfull/society/<slug:slug>/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='swapfull_society_detail'),



    #  ------ FOOTPRINTS ---
    # zero version of intro
    re_path('footprint/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroFootprintDetailView.as_view(), name='footprint_detail'),

    #  with slide number
    path('footprint/<slug:slug>/<slide_num>/', 
        views.FootprintDetailView.as_view(), name='footprint_slide_detail'),

    # default full - intro (changed Nov 1, 2017)
    path('footprint/<slug:slug>/', 
        views.IntroFullFootprintDetailView.as_view(), name='footprint_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/footprint/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='full_footprint_re_intro_detail'),


    #  full screen with slide number
    path('full/footprint/<slug:slug>/<slide_num>/', 
        views.FullFootprintDetailView.as_view(), name='full_footprint_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/footprint/<slug:slug>/', 
        views.IntroFootprintDetailView.as_view(), name='ajax_footprint_detail'),

    # re-use ReIntroFullFootprinDetailView
    path('swapfull/footprint/<slug:slug>/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='swapfull_footprint_detail'),


    #  ------ TEAM ---
    path('team/feature/', views.TeamFeatureListView.as_view(), \
        name='team_special_list'),

]

impressions/special/models.py
from django.db import models
from django.utils.html import format_html
from django.conf import settings
from impressions.core.models import AssociationMixin, Source # ContentType
from impressions.supporting.models import CommonSupportingModel

class Feature(CommonSupportingModel):
    """
    Special Features
    ContentType is defined in Admin in Core > ContentTypes
    """
    SPECIAL_TYPES = (
        ('slideshow','Slideshow'),
        ('video','Video Story'),
        ('voices','Voices'),
        ('looking','Looking &amp; Seeing'),
        ('then','Then &amp; Now'),
        ('footprint','Activity: Footprints'),
        ('explore','Activity: Explore'),
        ('discoverers','Whose Discovery'),
        ('society','Activity: Ladies Literary Society'),
    )
    FEATURE_CONTENT_TYPE_ID = 10
    content_type = models.ForeignKey('core.ContentType', 
        default=FEATURE_CONTENT_TYPE_ID, on_delete=models.CASCADE)
    special_type = models.CharField(max_length=32, default='slideshow', 
        choices=SPECIAL_TYPES)
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, default='')
    narrative = models.TextField('Narrative / Label', blank=True, default='')
    map_blurb = models.TextField(blank=True, default='')
    is_on_menu = models.BooleanField('Show on Special Features Menu', default=True)
    img_width = models.IntegerField('img width (or runtime)', blank=True, null=True)
    img_height = models.IntegerField(blank=True, null=True)

    # for menu - each type a separate list
    def slideshow_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='slideshow')

    def video_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='video')

    def voices_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='voices')

    def looking_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='looking')

    def then_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='then')

    # in the case of Activities we want to display only "Activities",
    # not the sub type
    def short_type_display(self):
        return self.get_special_type_display().split(":")[0]

    def image_img(self):
        return format_html('<img src="/static/special/menupics/' + self.slug + \
                    '.jpg" width="100" height="75"/>')    
    image_img.short_description = 'Thumb'

    def on_menu(self):
        # short name for display list
        return self.is_on_menu
    on_menu.short_description = 'menu'
    on_menu.boolean = True

    class Meta:
        verbose_name = "Special Feature"
        ordering = ['special_type', 'ordinal']
        
    def __str__(self):
        return str(self.status_num) + " - " + self.special_type + ": " + self.title


class Frame(models.Model):
    feature = models.ForeignKey('special.Feature', on_delete=models.CASCADE)
    slide_num = models.IntegerField()
    """
    help_text="File naming: olc/connections/static/connections/audiovisuals/slides/"\
    "short_name_1, short_name_2, etc.")
    """
    image_name = models.CharField('image short name', max_length=32, blank=True, 
        default='')
    caption = models.CharField(max_length=255, blank=True, default='',
            help_text="For each slide -- Slides ignore Caption at top of form.")
    source = models.ForeignKey('core.Source', default=1, on_delete=models.CASCADE)
    narrative = models.TextField(blank=True, default='',
            help_text="caption for each slide -- slides ignore Narrative at top of form.")
    num_correct = models.IntegerField(null=True, blank=True)
         
    # next, prev slide, false if none
    def get_next(self):
        next_list = Frame.objects.filter(feature_id=self.feature_id, 
            slide_num__gt=self.slide_num)
        if next_list:
            return next_list.first()
        return False

    # Special condition added to prevent going back to slide 0 which is the intro
    def get_prev(self):
        prev_list = Frame.objects.filter(feature_id=self.feature_id, 
            slide_num__lt=self.slide_num).order_by('-slide_num')
        if prev_list:
            prev = prev_list.first()
            if prev.slide_num > 0:
                return prev_list.first()
        return False

    class Meta:
        ordering = ['slide_num']
        
    def __str__(self):
        return self.feature.slug + "_" + str(self.slide_num) + "_" + self.image_name

templates/special/_slide_nav.html
{# link_class will either be swap_pop (normal for slmins, or noclas, for fullscreen) #}
<ul class="activities-controls">
	<li>
    {% if slide.get_prev %}
      <a class="{{ link_class }}"  
      href="{% url 'special:'|add:link_name object.slug slide.get_prev.slide_num %}">&lArr; Previous</a>
    {% else %}
      <span class="no-more">&lArr; Previous</span>
    {% endif %}
   &diams;
   <a class="{{ link_class }}"  
   href="{% url 'special:'|add:link_name object.slug 0 %}">Intro</a>
   &diams;
    {% if slide.get_next %}
      <a class="{{ link_class }}"  
      href="{% url 'special:'|add:link_name object.slug slide.get_next.slide_num %}">Next &rArr;</a>
    {% else %}
      <span class="no-more">Next &rArr;</span>
    {% endif %}
	</li>
</ul>

templates/special/discoverers-vote.html
{% extends extend_base %}
{% load static %}

{% block heading %}Your Vote{% endblock %}
{% block item_title %}You cast your vote for {{ votee_object.caption|safe }}! {% endblock %}

{% block slim_content%}

<section class="vote-feedback">

  <h3>Here's how other visitors to this website have voted:</h3>

  <ul>
  {% for slide in object.frame_set.all %}
    <li>
      {{slide.num_correct}} visitor votes -
      {% if slide.slide_num == votee_object.slide_num %}
        <span class="accent">{{slide.caption}}</span> (Your vote)
      {% else %}
        {{slide.caption}}
      {% endif %}
    </li>
  {% endfor %}
  </ul>


  <h3>Your vote makes sense because&hellip;</h3>
  <p>{{ votee_object.narrative|safe }}</p>

  <h3>But other votes could make sense because&hellip;</h3>

	{% for slide in object.frame_set.all %}
		{% if slide.slide_num != votee_object.slide_num %}
			<p><span class="heading">{{slide.caption}}</span><br/>
			{{slide.narrative|safe}}</p>
		{% endif %}
	{% endfor %}
	
</section>

{% endblock slim_content %}

templates/special/discoverers.html
{% extends extend_base %}
{% load static %}

{# This is a placeholder - in case we want to make a shell to display Disoverers stand-alone #}

{% block heading %}{{ object.content_type.plural_title }} - Discoverers intro {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

<section class="chapter">
	<div class="chapter-image">

		{% include "special/discoverers_includes/_whose-discovery-3.html" %}
	
	</div><!-- /video-content -->
</section>

{% endblock slim_content %}

templates/special/feature_detail.html
<p>Placeholder template with default name. If I can figure out how to tell FeatureDetailView to not need a template, this could go away.
</p>

templates/special/footprint.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Activity {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

<script type="text/javascript">
	var numOfCorrect = {{slide.num_correct}};
</script>

<script type="text/javascript">
	// since this is in a slim called by ajax we can't just list the script directly
	$.getScript('{% static "js/footprint.js" %}', function() {
	  // Set variable after script is loaded.
	  var numOfCorrect = {{slide.num_correct}};
	});
</script>

<section class="activity-col">
	{% block activity_image %}

		{% with "special/footprint_includes/_"|add:slide.image_name|add:".html" as template %}
		    {% include template %}
		{% endwith %}

	{% endblock activity_image %}
</section>

<section class="activity-controls-col">
	{% block activity_controls %}

		<h4 class="heading slim-subhead">How to:</h4>
	  <p>Click on the footprint(s) in each image. Click "show me" to reveal all the footprints. Click "next" to proceed.</p>
		
		<ul class="activities-controls">
			<li id="feedback">Feedback...</li>
			<li id="score">found: 0 of 4</li>
			<li><a class="show" href="#">show me</a></li>

			{% block full_links %}
			<li>
	          {% if slide.get_prev %}
	            <a class="{{ link_class }}"  
	            href="{% url 'special:'|add:link_name object.slug slide.get_prev.slide_num %}">&lArr; Previous</a>
	          {% else %}
	            <span class="no-more">&lArr; Previous</span>
	          {% endif %}
	         &diams;
	         <a class="{{ link_class }}"  href="{% url 'special:'|add:link_name object.slug 0 %}">Intro</a>
	         &diams;
	          {% if slide.get_next %}
	            <a class="{{ link_class }}"  
	            href="{% url 'special:'|add:link_name object.slug slide.get_next.slide_num %}">Next &rArr;</a>
	          {% else %}
	            <span class="no-more">Next &rArr;</span>
	          {% endif %}
			</li>
			{% endblock full_links %}

		</ul>

	{% endblock activity_controls %}
</section>

{% endblock slim_content %}

templates/special/looking.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Looking &amp; Seeing {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}


  {{ object.description|safe }}
  
  <!-- from Cod Rops -->
  {# using img_width field for audio total run time. #}
  <div class="audio-slideshow" data-audio="{{ MEDIA_URL }}special/looking/media/{{ object.slug }}.m4a" data-audio-duration="{{ object.img_width }}">
    
    <div class="audio-slides">
    {% for slide in object.frame_set.all %}
      <img src="{{ MEDIA_URL }}special/looking/fullpics/{{ slide.image_name }}.jpg" data-thumbnail="{{ MEDIA_URL }}special/looking/thumbpics/{{ slide.image_name }}.jpg" data-slide-time="{{ slide.num_correct }}">

    {% endfor %}
    </div><!-- /audio-slides -->

    <div class="audio-control-interface">

      <div class="play-pause-container">
        <a href="javascript:;" class="audio-play" tabindex="1">Play</a>
        <a href="javascript:;" class="audio-pause" tabindex="1">Pause</a>
      </div><!-- /play-pause-container -->

      <div class="time-container">
        <span class="play-time"></span> / <span class="total-time"></span>
      </div><!-- /time-container -->

      <div class="timeline">
        <div class="timeline-controls"></div>
        <div class="playhead"></div>
      </div><!-- /timeline -->

      <div class="jplayer"></div>

    </div><!-- /audio-control-interface -->

  </div><!-- /audio-slideshow -->

  <!-- /from Cod Rops -->
  <script type="text/javascript">
    // since this is in a slim called by ajax we can't just list the script directly
    $.getScript('{% static "js/jquery.audioslideshow.js" %}', function() {
      // Call custom function defined in script
      $('.audio-slideshow').audioSlideshow();
    });
  </script>

  <div class="looking-credits">
    {{ object.narrative|safe }}
  </div>


{% endblock slim_content %}

templates/special/slideshow.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Slideshow {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}
	
  {# shared with swap_fullpop ajax #}
  {# wish I could include here, but then intro, which extends this, doesn't see block controls #}
  {# I have to hack an extra version of intro as well!! #}
  {# include 'special/slim_content_includes/_slideshow.html' #}


<section class="slideshow-col">
	<div id="slideshow-image">

		<img src="{{ MEDIA_URL }}special/slideshow/fullpics/{{ slide.image_name }}.jpg" class="double-border">
    <p class="caption slim-caption">{{ slide.caption }} Image courtesy of {{ slide.source.institution|safe }}.</p>

	</div> <!-- slideshow-image -->
</section>

<section class="slideshow-controls-col">
  {% block slideshow_controls %}

    {% include 'special/_slide_nav.html' %}

    <h4 class="heading slim-subhead">About this Image</h4>

    {% if error_msg %}
      <p class="error-msg">{{ error_msg }}</p>
    {% else %}
      <p>{{ slide.narrative|safe}}</p>
    {% endif %}


  {% endblock slideshow_controls %}
</section>


{% endblock slim_content %}

templates/special/slideshow_intro.html
{% extends "special/slideshow.html" %}
{% load static %}

{% block slideshow_controls %}

  <h4 class="heading slim-subhead">About this Slideshow</h4>

	{% if error_msg %}
	  <p class="error-msg">{{ error_msg }}</p>
	{% else %}
	  <p>{{ slide.narrative|safe}}</p>
	{% endif %}

	<ul class="activities-controls">
		<li>
			<a class="{{ link_class }}" 
		    href="{% url 'special:'|add:link_name object.slug 1 %}">View Slideshow &rArr;</a>
		</li>
	</ul>
	
{% endblock slideshow_controls %}

templates/special/society.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Activity {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

  {# shared with swap_fullpop ajax #}
  {# include 'special/slim_content_includes/_society.html' #}

	<img src="{{ MEDIA_URL }}special/society/fullpics/{{ slide.image_name }}.jpg" class="double-border">

	{% block optional_intro %}
	  {% if error_msg %}
	    <p class="error-msg">{{ error_msg }}</p>
	  {% else %}
	    <p class="society-question">{{ slide.narrative}}</p>
	  {% endif %}

	  <div id="society_feedback">
	    <p>How would you answer this question?</p>
	  </div>

	  <form id="society_choices" action="#">

	    <!-- need to add slide num -->
	    <input class="society_choice" type="button"
	      name="{% url 'special:society_choice' object.slug slide.slide_num 1 %}" value="Affirmative" />
	    <input class="society_choice" type="button" 
	      name="{% url 'special:society_choice' object.slug slide.slide_num 0 %}" value="Negative" />

	  </form>
	      
	  <hr/>
	  <p class="slide-number">Question {{ slide.slide_num }} of 14</p>

	  {% block slideshow_controls %}
	    {% include 'special/_slide_nav.html' %}
	  {% endblock slideshow_controls %}

	{% endblock optional_intro %}


{% endblock slim_content %}

templates/special/society_choice.html
      <span class="accent">{{ feedback|safe }}</span>

templates/special/society_intro.html
{% extends "special/society.html" %}
{% load static %}

{% block optional_intro %}

  <h4 class="heading slim-subhead">About this Activity</h4>

	{% if error_msg %}
	  <p class="error-msg">{{ error_msg }}</p>
	{% else %}
	  <p>{{ slide.narrative}}</p>
	{% endif %}

	<ul class="activities-controls">
		<li>
			<a class="{{ link_class }}" 
		    href="{% url 'special:'|add:link_name object.slug 1 %}">Start Quiz &rArr;</a>
		</li>
	</ul>
	
{% endblock optional_intro %}

templates/special/then.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Then &amp; Now {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

<!-- d3.min.js' needs to be called in head -->

<div class="svg-container-then-{{ object.slug }}">
	
	<svg class="iefix-special double-border" version="1.1" viewbox="0 0 {{ object.img_width }} {{ object.img_height }}"> <!-- 562 width="100%" height="100%" -->
	<g transform="translate(0,0)">
	  <!-- <clipPath id="clip">
	    <circle cx="333" cy="127.5" r="100"></circle>
	  </clipPath> -->
	  <image x="0" y="0" xlink:href="{{ MEDIA_URL }}special/then/fullpics/{{ slide.image_name }}.jpg" 
	  	width="{{ object.img_width }}" height="{{ object.img_height }}"/>

	  <image xlink:href="{{ MEDIA_URL }}special/then/fullpics/{{ slide.get_next.image_name }}.jpg" 
	  	width="{{ object.img_width }}" height="{{ object.img_height }}" id="doc-image" />
	</g>
	</svg>
</div> <!-- svg-container -->

<!-- <script src="{% static 'js/lens-d3.js' %}" type="text/javascript"></script> -->
<script type="text/javascript">
	// since this is in a slim called by ajax we can't just list the script directly
	$.getScript("{% static 'js/lens-d3.js' %}");
</script>


<p class="caption slim-caption">{{ object.caption }} Image courtesy of 
{{ object.source.institution|safe }}.</p>

{{ object.narrative|safe }}

{% endblock slim_content %}

templates/special/video.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Video Story {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

<div id="video-content">

	<video width="300" height="168" controls="controls">
		<source src="{{ MEDIA_URL }}special/video/media/{{ object.slug}}.webm" type="video/webm">
		<source src="{{ MEDIA_URL }}special/video/media/{{ object.slug}}.mp4" type="video/mp4">
		Your browser does not support the video tag.
	</video>

</div><!-- /video-content -->

	{{ object.narrative|safe }}

{% endblock slim_content %}

templates/special/voices.html
{% extends extend_base %}
{% load static %}

{% block heading %}{{ object.content_type.plural_title }} - Voices {% endblock %}
{% block item_title %}{{ object.title|safe }}{% endblock %}

{% block slim_content%}

  {{ object.description|safe }}

  <audio controls>
    <source src="{{ MEDIA_URL }}special/voices/media/{{ object.slug }}.m4a" 
      type="audio/mpeg" />
    <source src="{{ MEDIA_URL }}special/voices/media/{{ object.slug }}.ogg" 
      type="audio/ogg" />
    <!-- fallback -->
       Your browser does not support the HTML5 audio element; instead you can 
       <a href="{{ MEDIA_URL }}special/voices/media/{{ object.slug }}.mp3">download 
        this MP3 audio file.</a>
  </audio>

  <blockquote>

	{{ object.narrative|safe }}
    
  <cite>{{ object.caption|safe }} </cite> 

  </blockquote>

{% endblock slim_content %}