config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url('admin/', admin.site.urls),
    path('ancillary/', include('impressions.ancillary.urls', namespace='ancillary')),
    path('', include('impressions.core.urls', namespace='core')),
    path('map/', include('impressions.map.urls', namespace='map')),
    path('special/', include('impressions.special.urls', namespace='special')),
    path('stories/', include('impressions.stories.urls', namespace='stories')),
    path('supporting/', include('impressions.supporting.urls', namespace='supporting')),
    path('themes/', include('impressions.themes.urls', namespace='themes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Also ensure static files are served
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

impressions/special/urls.py
from django.urls import path, re_path
from . import views

app_name="special"

urlpatterns = [
    path('feature/', views.FeatureListView.as_view(), name='feature_list'),

    # CBV approach
    # The first part of each name has to match the corresponding
    # name in special.Feature.special_type, e.g. "video"_detail
    # Applies only to the "staring" names, not subsequent slide details

    # ----------- NON-SLIDE FEATURES ---------

    #  ------ VIDEO ---
    path('video/<slug:slug>/', 
        views.FullVideoDetailView.as_view(), name='video_detail'),

    path('ajax/video/<slug:slug>/', 
        views.VideoDetailView.as_view(), name='ajax_video_detail'),

    path('swapfull/video/<slug:slug>/', 
        views.SwapFullVideoDetailView.as_view(), name='swapfull_video_detail'),

    #  ------ VOICE ---
    # Should have been voice, singular, but too hard to change now
    path('voices/<slug:slug>/', 
        views.FullVoiceDetailView.as_view(), name='voices_detail'),

    path('ajax/voices/<slug:slug>/', 
        views.VoiceDetailView.as_view(), name='ajax_voices_detail'),

    path('swapfull/voices/<slug:slug>/', 
        views.SwapFullVoiceDetailView.as_view(), name='swapfull_voices_detail'),

    #  ------ EXPLORE ---
    path('explore/<slug:slug>/', 
        views.FullExploreDetailView.as_view(), name='explore_detail'),

    path('ajax/explore/<slug:slug>/', 
        views.ExploreDetailView.as_view(), name='ajax_explore_detail'),

    path('swapfull/explore/<slug:slug>/', 
        views.SwapFullExploreDetailView.as_view(), name='swapfull_explore_detail'),

    #  ------ DICOVERERS ---
    # Not stand-alone -- only serves voting in Whose Discovery, Chapter 8
    path('discoverers/<slug:slug>/<slide_num>/', 
        views.DiscoverersDetailView.as_view(), name='discoverers_detail'),

    # ----------- SLIDE-BASED FEATURES ---------

    #  ------ THEN AND NOW ---
    path('then/<slug:slug>/', 
        views.FullThenDetailView.as_view(), name='then_detail'),

    path('ajax/then/<slug:slug>/', 
        views.ThenDetailView.as_view(), name='ajax_then_detail'),

    path('swapfull/then/<slug:slug>/', 
        views.SwapFullThenDetailView.as_view(), name='swapfull_then_detail'),

    #  ------ LOOKING ---
    path('looking/<slug:slug>/', 
        views.FullLookingDetailView.as_view(), name='looking_detail'),

    path('ajax/looking/<slug:slug>/', 
        views.LookingDetailView.as_view(), name='ajax_looking_detail'),

    path('swapfull/looking/<slug:slug>/', 
        views.SwapFullLookingDetailView.as_view(), name='swapfull_looking_detail'),


    #  ------ SLIDESHOW ---
    # Zero param must also go to intro. We're dependent on the link_name 
    # which distinguishes full from slim pop, so we can't just use 
    # slideshow_detail (no int param) for the link in nav
    re_path('slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.IntroSlideshowDetailView.as_view(), name='reintro-slideshow_detail'),

    #  with slide number (other than 0)
    path('slideshow/<slug:slug>/<slide_num>/', 
        views.SlideshowDetailView.as_view(), name='slideshow_slide_detail'),

    # default - full (changed Nov 1, 2017)
    path('slideshow/<slug:slug>/', 
        views.IntroFullSlideshowDetailView.as_view(), name='slideshow_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='full_slideshow_re_intro_detail'),

    #  full screen with slide number
    path('full/slideshow/<slug:slug>/<slide_num>/', 
        views.FullSlideshowDetailView.as_view(), name='full_slideshow_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/slideshow/<slug:slug>/', 
        views.IntroSlideshowDetailView.as_view(), name='intro_ajax_slideshow_detail'),

    # the moment when you come from a see also on a person full slim
    # re-use ReIntroFullSlideshowDetailView
    path('swapfull/slideshow/<slug:slug>/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='swapfull_slideshow_detail'),


    #  ------ SOCIETY ---
    # choice for vote
    path('society/choice/<slug:slug>/<slide_num>/<int:choice>)/', 
        views.SocietyChoiceDetailView.as_view(), name='society_choice'),

    # zero version of intro
    re_path('society/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroSocietyDetailView.as_view(), name='society_detail'),

    #  with slide number
    path('society/<slug:slug>/<slide_num>/', 
        views.SocietyDetailView.as_view(), name='society_slide_detail'),

    # default - intro (changed Nov 1, 2017)
    path('society/<slug:slug>/', 
        views.IntroFullSocietyDetailView.as_view(), name='society_detail'),


    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/society/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='full_society_re_intro_detail'),

    #  full screen with slide number
    path('full/society/<slug:slug>/<slide_num>/', 
        views.FullSocietyDetailView.as_view(), name='full_society_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/society/<slug:slug>/', 
        views.IntroSocietyDetailView.as_view(), name='ajax_society_detail'),

    # re-use ReIntroFullSocietyDetailView
    path('swapfull/society/<slug:slug>/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='swapfull_society_detail'),



    #  ------ FOOTPRINTS ---
    # zero version of intro
    re_path('footprint/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroFootprintDetailView.as_view(), name='footprint_detail'),

    #  with slide number
    path('footprint/<slug:slug>/<slide_num>/', 
        views.FootprintDetailView.as_view(), name='footprint_slide_detail'),

    # default full - intro (changed Nov 1, 2017)
    path('footprint/<slug:slug>/', 
        views.IntroFullFootprintDetailView.as_view(), name='footprint_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/footprint/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='full_footprint_re_intro_detail'),


    #  full screen with slide number
    path('full/footprint/<slug:slug>/<slide_num>/', 
        views.FullFootprintDetailView.as_view(), name='full_footprint_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/footprint/<slug:slug>/', 
        views.IntroFootprintDetailView.as_view(), name='ajax_footprint_detail'),

    # re-use ReIntroFullFootprinDetailView
    path('swapfull/footprint/<slug:slug>/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='swapfull_footprint_detail'),


    #  ------ TEAM ---
    path('team/feature/', views.TeamFeatureListView.as_view(), \
        name='team_special_list'),

]

impressions/supporting/urls.py
from django.urls import path
from . import views

app_name="supporting"

urlpatterns = [
    # aka Backgrounds
    path('context/', views.ContextListView.as_view(paginate_by=20), 
        name='context_list'),
    path('context/<int:pk>/', views.ContextDetailView.as_view(), 
        name='context_detail_pk'),
    path('context/<slug:slug>/', views.FullContextDetailView.as_view(), 
        name='context_detail'),
    path('ajax/context/<slug:slug>/', 
        views.ContextDetailView.as_view(), name='ajax_context_detail'),
    #  full screen from swap fullpop
    path('swapfull/context/<slug:slug>/', 
        views.SwapFullContextDetailView.as_view(), name='swapfull_context_detail'),


    # --- EVIDENCE ITEMS --
    path('evidenceitem/', views.EvidenceItemListView.as_view(paginate_by=20), 
        name='evidenceitem_list'), 

    # only for team lists - still used?
    path('evidenceitem/<int:pk>/', views.EvidenceItemDetailView.as_view(), 
        name='evidenceitem_detail_pk'),
    # supports ajax for both artifact and document pages
    # with page suffix - ajax
    path('evidence/<slug:slug>/<page_suffix>/', 
        views.evidence_page, name='evidence_page_detail'),  

    # is_document_oriented evidenceitems need separate view that supplies 1st page
    path('document/<slug:slug>/', views.FullDocumentDetailView.as_view(), 
      name='document_detail'),

    #  ajax 
    path('ajax/document/<slug:slug>/', 
        views.DocumentDetailView.as_view(), name='ajax_document_detail'),

    path('swapfull/document/<slug:slug>/', 
        views.SwapFullDocumentDetailView.as_view(), name='swapfull_document_detail'),

    # non is_document_oriented evidenceitems (artifacts) default to no page info
    path('artifact/<slug:slug>/', views.FullArtifactDetailView.as_view(), 
      name='artifact_detail'),
    #  ajax 
    path('ajax/artifact/<slug:slug>/', 
        views.ArtifactDetailView.as_view(), name='ajax_artifact_detail'),

    path('swapfull/artifact/<slug:slug>/', 
        views.SwapFullArtifactDetailView.as_view(), name='swapfull_artifact_detail'),

    # --- PEOPLE
    path('person/', views.PersonListView.as_view(), name='person_list'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), 
        name='person_detail_pk'),
    # url('person/<slug:slug>/', views.PersonDetailView.as_view(), 
    #     name='person_detail'),
    # # full screen mobile
    # url('full/person/<slug:slug>/', 
    #     views.FullPersonDetailView.as_view(), name='full_person_detail'),
    path('ajax/person/<slug:slug>/', views.PersonDetailView.as_view(), 
        name='ajax_person_detail'),
    # full screen mobile
    path('person/<slug:slug>/', 
        views.FullPersonDetailView.as_view(), name='person_detail'),
    #  full screen from swap fullpop
    path('swapfull/person/<slug:slug>/', 
        views.SwapFullPersonDetailView.as_view(), name='swapfull_person_detail'),

    # aka In Briefs
    path('fastfact/<int:pk>/', views.FastFactDetailView.as_view(), 
        name='fastfact_detail_pk'),
    path('fastfact/<slug:slug>/', views.FullFastFactDetailView.as_view(), 
        name='fastfact_detail'),
    path('ajax/fastfact/<slug:slug>/', 
        views.FastFactDetailView.as_view(), name='ajax_fastfact_detail'),
    

    # -- team pages  
    path('team/evidenceitem/', views.EvidenceItemListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_evidenceitem_list'),
    path('team/person/', views.PersonListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_person_list'),
    path('team/context/', views.ContextListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_context_list'),
    # url for special list in special/urls.py
    path('team/', views.TeamTemplateView.as_view(), name='team_type_list'),
    path('ziftest/', views.TemplateView.as_view(template_name='zif-test.html'), name='zif-test'),
]

impressions/special/models.py
from django.db import models
from django.utils.html import format_html
from django.conf import settings
from impressions.core.models import AssociationMixin, Source # ContentType
from impressions.supporting.models import CommonSupportingModel

class Feature(CommonSupportingModel):
    """
    Special Features
    ContentType is defined in Admin in Core > ContentTypes
    """
    SPECIAL_TYPES = (
        ('slideshow','Slideshow'),
        ('video','Video Story'),
        ('voices','Voices'),
        ('looking','Looking &amp; Seeing'),
        ('then','Then &amp; Now'),
        ('footprint','Activity: Footprints'),
        ('explore','Activity: Explore'),
        ('discoverers','Whose Discovery'),
        ('society','Activity: Ladies Literary Society'),
    )
    FEATURE_CONTENT_TYPE_ID = 10
    content_type = models.ForeignKey('core.ContentType', 
        default=FEATURE_CONTENT_TYPE_ID, on_delete=models.CASCADE)
    special_type = models.CharField(max_length=32, default='slideshow', 
        choices=SPECIAL_TYPES)
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, default='')
    narrative = models.TextField('Narrative / Label', blank=True, default='')
    map_blurb = models.TextField(blank=True, default='')
    is_on_menu = models.BooleanField('Show on Special Features Menu', default=True)
    img_width = models.IntegerField('img width (or runtime)', blank=True, null=True)
    img_height = models.IntegerField(blank=True, null=True)

    # for menu - each type a separate list
    def slideshow_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='slideshow')

    def video_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='video')

    def voices_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='voices')

    def looking_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='looking')

    def then_list(self):
        return Feature.objects.filter(status_num__gte=settings.STATUS_LEVEL, 
            is_on_menu=True, special_type='then')

    # in the case of Activities we want to display only "Activities",
    # not the sub type
    def short_type_display(self):
        return self.get_special_type_display().split(":")[0]

    def image_img(self):
        return format_html('<img src="/static/special/menupics/' + self.slug + \
                    '.jpg" width="100" height="75"/>')    
    image_img.short_description = 'Thumb'

    def on_menu(self):
        # short name for display list
        return self.is_on_menu
    on_menu.short_description = 'menu'
    on_menu.boolean = True

    class Meta:
        verbose_name = "Special Feature"
        ordering = ['special_type', 'ordinal']
        
    def __str__(self):
        return str(self.status_num) + " - " + self.special_type + ": " + self.title


class Frame(models.Model):
    feature = models.ForeignKey('special.Feature', on_delete=models.CASCADE)
    slide_num = models.IntegerField()
    """
    help_text="File naming: olc/connections/static/connections/audiovisuals/slides/"\
    "short_name_1, short_name_2, etc.")
    """
    image_name = models.CharField('image short name', max_length=32, blank=True, 
        default='')
    caption = models.CharField(max_length=255, blank=True, default='',
            help_text="For each slide -- Slides ignore Caption at top of form.")
    source = models.ForeignKey('core.Source', default=1, on_delete=models.CASCADE)
    narrative = models.TextField(blank=True, default='',
            help_text="caption for each slide -- slides ignore Narrative at top of form.")
    num_correct = models.IntegerField(null=True, blank=True)
         
    # next, prev slide, false if none
    def get_next(self):
        next_list = Frame.objects.filter(feature_id=self.feature_id, 
            slide_num__gt=self.slide_num)
        if next_list:
            return next_list.first()
        return False

    # Special condition added to prevent going back to slide 0 which is the intro
    def get_prev(self):
        prev_list = Frame.objects.filter(feature_id=self.feature_id, 
            slide_num__lt=self.slide_num).order_by('-slide_num')
        if prev_list:
            prev = prev_list.first()
            if prev.slide_num > 0:
                return prev_list.first()
        return False

    class Meta:
        ordering = ['slide_num']
        
    def __str__(self):
        return self.feature.slug + "_" + str(self.slide_num) + "_" + self.image_name

templates/special/discoverers_includes/_whose-discovery-1.html
{% load static %}

{# since this is a one-off we're just building the table by hand #}
<table class="discoverers-faces">
  <tr>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-moody' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/pliny-moody.jpg">
        <span class="name">Pliny Moody</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-native' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/native-american.jpg">
        <span class="name">Native American</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-hitchcock' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/edward-hitchcock.jpg">
        <span class="name">Edward Hitchcock</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-marsh' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/dexter-marsh.jpg">
        <span class="name">Dexter Marsh</span></a>
    </td>
  </tr>
  <tr>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-deane' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/james-deane.jpg">
        <span class="name">James Deane</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-field' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/roswell-field.jpg">
        <span class="name">Roswell Field</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-silliman' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/benjamin-silliman.jpg">
        <span class="name">Benjamin Silliman</span></a>
    </td>
    <td>
      <a class="pop_item" href="{% url 'special:voices_detail' 'who-draper' %}">
        <img src="{{ MEDIA_URL }}special/discoverers/menupics/william-draper.jpg">
        <span class="name">William Draper</span></a>
    </td>
  </tr>
</table>

templates/special/discoverers_includes/_whose-discovery-8.html
{% load static %}

<form id="discoverers-form" action="#">
  <table class="discoverers-faces">
    <tr>
      <td>
      <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-moody' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/pliny-moody.jpg">
          <span class="name">Pliny Moody</span>
        </a>  
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-moody' %}">MY CASE</a>
          <label for="moody">VOTE:</label>
          <input type="checkbox" class="vote" id="moody" value="0">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-native' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/native-american.jpg">
          <span class="name">Native American</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-native' %}">MY CASE</a>
          <label for="native">VOTE:</label>
          <input type="checkbox" class="vote" id="native" value="1">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-hitchcock' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/edward-hitchcock.jpg">
          <span class="name">Edward Hitchcock</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-hitchcock' %}">MY CASE</a>
          <label for="hitchcock">VOTE:</label>
          <input type="checkbox" class="vote" id="hitchcock" value="2">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-marsh' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/dexter-marsh.jpg">
          <span class="name">Dexter Marsh</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-marsh' %}">MY CASE</a>
          <label for="marsh">VOTE:</label>
          <input type="checkbox" class="vote" id="marsh" value="3">
        </div>
      </td>

    </tr>

    <tr>
      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-deane' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/james-deane.jpg">
          <span class="name">James Deane</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-deane' %}">MY CASE</a>
          <label for="deane">VOTE:</label>
          <input type="checkbox" class="vote" id="deane" value="4">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-field' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/roswell-field.jpg">
          <span class="name">Roswell Field</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-field' %}">MY CASE</a>
          <label for="field">VOTE:</label>
          <input type="checkbox" class="vote" id="field" value="5">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-silliman' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/benjamin-silliman.jpg">
          <span class="name">Benjamin Silliman</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-silliman' %}">MY CASE</a>
          <label for="silliman">VOTE:</label>
          <input type="checkbox" class="vote" id="silliman" value="6">
        </div>
      </td>

      <td>
        <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-draper' %}">
          <img src="{{ MEDIA_URL }}special/discoverers/menupics/william-draper.jpg">
          <span class="name">William Draper</span>
        </a>
        <div class="discoverers-vote">
          <a class="pop_item" href="{% url 'supporting:fastfact_detail' 'case-draper' %}">MY CASE</a>
          <label for="draper">VOTE:</label>
          <input type="checkbox" class="vote" id="draper" value="7">
        </div>
      </td>

    </tr>

  </table>

</form>