config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url('admin/', admin.site.urls),
    path('ancillary/', include('impressions.ancillary.urls', namespace='ancillary')),
    path('', include('impressions.core.urls', namespace='core')),
    path('map/', include('impressions.map.urls', namespace='map')),
    path('special/', include('impressions.special.urls', namespace='special')),
    path('stories/', include('impressions.stories.urls', namespace='stories')),
    path('supporting/', include('impressions.supporting.urls', namespace='supporting')),
    path('themes/', include('impressions.themes.urls', namespace='themes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Also ensure static files are served
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

impressions/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    # a place-holder -- not triggered by js because there is no "mobile menu"
    # to be visible or not
    path('home/intro/page/', views.FullIntroTemplateView.as_view(), name='home_intro'),
    # needed to add third element "page" to match the length of all other urls
    # using full vs. ajax
    path('home/ajax/intro/page/', views.IntroTemplateView.as_view(), name='ajax_home_intro'),
    path('team/', views.TeamHomeTemplateView.as_view(), name='team_home'),
    path('sitemap/', views.SitemapTemplateView.as_view(), name='sitemap'),
]

impressions/stories/urls.py
from django.urls import path
from . import views

app_name="stories"

urlpatterns = [
    path('', views.StoryListView.as_view(), name='story_list'),
    path('team/', 
        views.StoryListView.as_view(template_name="stories/team_story_list.html"), 
    	name='team_story_list'),
    path('team/<slug:slug>/', 
        views.StoryDetailView.as_view(template_name="stories/team_story_detail.html"), 
    	name='team_story_detail'),
    path('<slug:slug>/<chapter_num>/', views.ChapterDetailView.as_view(), 
    	name='chapter_detail'),
    path('<slug:slug>/', views.StoryDetailView.as_view(), name='story_detail'),
]

impressions/supporting/urls.py
from django.urls import path
from . import views

app_name="supporting"

urlpatterns = [
    # aka Backgrounds
    path('context/', views.ContextListView.as_view(paginate_by=20), 
        name='context_list'),
    path('context/<int:pk>/', views.ContextDetailView.as_view(), 
        name='context_detail_pk'),
    path('context/<slug:slug>/', views.FullContextDetailView.as_view(), 
        name='context_detail'),
    path('ajax/context/<slug:slug>/', 
        views.ContextDetailView.as_view(), name='ajax_context_detail'),
    #  full screen from swap fullpop
    path('swapfull/context/<slug:slug>/', 
        views.SwapFullContextDetailView.as_view(), name='swapfull_context_detail'),


    # --- EVIDENCE ITEMS --
    path('evidenceitem/', views.EvidenceItemListView.as_view(paginate_by=20), 
        name='evidenceitem_list'), 

    # only for team lists - still used?
    path('evidenceitem/<int:pk>/', views.EvidenceItemDetailView.as_view(), 
        name='evidenceitem_detail_pk'),
    # supports ajax for both artifact and document pages
    # with page suffix - ajax
    path('evidence/<slug:slug>/<page_suffix>/', 
        views.evidence_page, name='evidence_page_detail'),  

    # is_document_oriented evidenceitems need separate view that supplies 1st page
    path('document/<slug:slug>/', views.FullDocumentDetailView.as_view(), 
      name='document_detail'),

    #  ajax 
    path('ajax/document/<slug:slug>/', 
        views.DocumentDetailView.as_view(), name='ajax_document_detail'),

    path('swapfull/document/<slug:slug>/', 
        views.SwapFullDocumentDetailView.as_view(), name='swapfull_document_detail'),

    # non is_document_oriented evidenceitems (artifacts) default to no page info
    path('artifact/<slug:slug>/', views.FullArtifactDetailView.as_view(), 
      name='artifact_detail'),
    #  ajax 
    path('ajax/artifact/<slug:slug>/', 
        views.ArtifactDetailView.as_view(), name='ajax_artifact_detail'),

    path('swapfull/artifact/<slug:slug>/', 
        views.SwapFullArtifactDetailView.as_view(), name='swapfull_artifact_detail'),

    # --- PEOPLE
    path('person/', views.PersonListView.as_view(), name='person_list'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), 
        name='person_detail_pk'),
    # url('person/<slug:slug>/', views.PersonDetailView.as_view(), 
    #     name='person_detail'),
    # # full screen mobile
    # url('full/person/<slug:slug>/', 
    #     views.FullPersonDetailView.as_view(), name='full_person_detail'),
    path('ajax/person/<slug:slug>/', views.PersonDetailView.as_view(), 
        name='ajax_person_detail'),
    # full screen mobile
    path('person/<slug:slug>/', 
        views.FullPersonDetailView.as_view(), name='person_detail'),
    #  full screen from swap fullpop
    path('swapfull/person/<slug:slug>/', 
        views.SwapFullPersonDetailView.as_view(), name='swapfull_person_detail'),

    # aka In Briefs
    path('fastfact/<int:pk>/', views.FastFactDetailView.as_view(), 
        name='fastfact_detail_pk'),
    path('fastfact/<slug:slug>/', views.FullFastFactDetailView.as_view(), 
        name='fastfact_detail'),
    path('ajax/fastfact/<slug:slug>/', 
        views.FastFactDetailView.as_view(), name='ajax_fastfact_detail'),
    

    # -- team pages  
    path('team/evidenceitem/', views.EvidenceItemListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_evidenceitem_list'),
    path('team/person/', views.PersonListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_person_list'),
    path('team/context/', views.ContextListView.as_view(template_name=\
        "supporting/team_item_list.html"), name='team_context_list'),
    # url for special list in special/urls.py
    path('team/', views.TeamTemplateView.as_view(), name='team_type_list'),
    path('ziftest/', views.TemplateView.as_view(template_name='zif-test.html'), name='zif-test'),
]

impressions/stories/models.py
from django.db import models
from impressions.core.models import ContentType, CommonModel, AssociationMixin, Source

class Story(CommonModel):
    STATUS_NUMS = (
        (0,'0 - Initial Entry'),
        (1,'1 - In Admin Only'),
        (2,'2 - Development (Wireframe)'),
        (3,'3 - Candidate for Publication'),
        (4,'4 - Published'),
    )
    STORY_CONTENT_TYPE_ID = 1
    content_type = models.ForeignKey('core.ContentType', default=STORY_CONTENT_TYPE_ID, on_delete=models.CASCADE)
    title = models.CharField(max_length=48)
    subtitle = models.CharField(max_length=64, blank=True, default='')
    image_name = models.CharField(max_length=32, blank=True, default='')
    introduction = models.TextField(blank=True, default='')
    status_num = models.IntegerField(default=0, choices=STATUS_NUMS)
    caption = models.CharField('Image Caption', max_length=255, blank=True, default='')
    source = models.ForeignKey('core.Source', default=1, on_delete=models.CASCADE)

    # next, prev story, false if none
    def get_next(self):
        next = Story.objects.filter(status_num__gt=1, ordinal__gt=self.ordinal)
        if next:
            return next.first()
        return False

    def get_prev(self):
        prev = Story.objects.filter(status_num__gt=1, 
            ordinal__lt=self.ordinal).order_by('-ordinal')
        if prev:
            return prev.first()
        return False

    def story_list(self):
        return Story.objects.filter(status_num__gt=1)

    def chapter_list(self):
        return Chapter.objects.filter(story_id=self.id)

    class Meta:
        ordering = ['ordinal']


class Chapter(AssociationMixin, models.Model):
    story = models.ForeignKey('stories.Story', on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    chapter_num = models.IntegerField(default=0)
    image_name = models.CharField(max_length=32, blank=True, default='')
    narrative = models.TextField(blank=True, default='')
    caption = models.CharField('Image Caption', max_length=255, blank=True, default='')
    source = models.ForeignKey('core.Source', default=1, on_delete=models.CASCADE)
    is_vertical = models.BooleanField(default=False)
    has_include = models.BooleanField('Use include instead of image',default=False)
    include_path = models.CharField(max_length=64, blank=True, default='')
    # contexts, people and evidence manys supplied by Association Mixin
    fastfacts = models.ManyToManyField('supporting.FastFact', 
        verbose_name='Fast Facts related to this item', blank=True)
    featured_specials = models.ManyToManyField('special.Feature', 
        verbose_name='Special Features related to this item', blank=True)

    # next chapter, empty if none
    def get_next(self):
        next = Chapter.objects.filter(story_id=self.story_id, 
            chapter_num__gt=self.chapter_num)
        if next:
            return next.first()
        return False

    def get_prev(self):
        prev = Chapter.objects.filter(story_id=self.story_id, 
            chapter_num__lt=self.chapter_num).order_by('-chapter_num')
        if prev:
            return prev.first()
        return False

    class Meta:
        ordering = ['story', 'chapter_num']

    def __str__(self):
        return self.title

impressions/stories/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.conf import settings
from .models import Story, Chapter

class StoryListView(ListView):
    model = Story
    queryset = Story.objects.filter(status_num__gte=settings.STATUS_LEVEL)
    # context_object_name = 'object_list'
    # template_name = 'stories/story_list.html' 


class StoryDetailView(DetailView):
    model = Story
    # context_object_name = 'object'
    # template_name = 'stories/story_detail.html'

class ChapterDetailView(DetailView):
    """
    Two parameters are sent: slug and chapter_num
    Slug finds the story. From there we just have to find the right chapter
    (We're not going directly by chapter pk, and chapters don't have slugs)
    """
    model = Story
    # context_object_name = 'object'
    template_name = 'stories/chapter_detail.html'

    # get the actual chapter    
    def get_context_data(self, **kwargs):
        # get context
        context = super(ChapterDetailView, self).get_context_data(**kwargs)
        # get story object from detail view
        story_object = super(ChapterDetailView, self).get_object()
        # chapter_num will come from parameters
        chapter_num_arg = self.kwargs['chapter_num']
        # get the chapter object
        chapter = get_object_or_404(Chapter, story_id=story_object.id, 
            chapter_num=chapter_num_arg)
        # set the chapter object in the context
        context['chapter'] = chapter
        # We need next and previous chapter numbers for navigation
        # get_next, get_prev set by properties in Chapter model

        return context
    

templates/stories/chapter_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Impressions - Story: {{object.title }}{% endblock %}

<!-- possibly migrate the following to a common story template -->
{% block wrapper_class %}"content-wrapper"{% endblock wrapper_class %}

{% block content_area %}

  <header>
    
    <h4 class="heading"><a href="{% url 'stories:story_detail' object.slug %}">{{ object.title|safe }}</a></h4>  
    <h2 class="main-title">Chapter {{ chapter.chapter_num }}: {{ chapter.title|safe }}</h2> 

    <nav>
      <ul class="chapter-nav heading">

          {% if chapter.get_prev %}
            <li><a href="{% url 'stories:chapter_detail' object.slug chapter.get_prev.chapter_num %}"> 
              &#8826; Previous</a></li>
          {% else %}
            <li>&#8826; Previous</li>
          {% endif %}
          <li>&diams;</li>
          <li class="chapter-nav--dropdown"><a href="#">Chapters &#8910;</a>

            <ol class="chapter-subnav">
            {% for nav_chapter in object.chapter_list %}
              <li><a href="{% url 'stories:chapter_detail' object.slug nav_chapter.chapter_num %}">
              {{ nav_chapter.chapter_num }}. {{ nav_chapter.title|safe }}</a></li>
            {% endfor %}  
            </ol>

          </li>
          <li>&diams;</li>
          {% if chapter.get_next %}
            <li><a href="{% url 'stories:chapter_detail' object.slug chapter.get_next.chapter_num %}">Next &#8827;</a></li>
          {% else %}
            Next &#8827;
          {% endif %}
      </ul>
    </nav>

  </header>

  <section class="chapter{% if chapter.is_vertical %}-vertical{% endif %}">
    <div class="chapter-image{% if chapter.is_vertical %}-vertical{% endif %}">

    {% if chapter.has_include %}
      {% include chapter.include_path %}
    {% else %}
        <img src="{{ MEDIA_URL }}stories/{{ object.slug }}/{{ chapter.image_name }}.jpg" alt="chapter illustration">
    {% endif %}

    <p class="caption">{{ chapter.caption|safe }}
      {% if chapter.source.id != 1 %}
        Image courtesy of {{ chapter.source.institution|safe }}.
      {% endif %}
    </p>

    </div><!--/chapter-image -->

    {{ chapter.narrative|safe }}

    {% if chapter.get_next %}
      <p><a href="{% url 'stories:chapter_detail' object.slug chapter.get_next.chapter_num %}">Next chapter: <em>{{ chapter.get_next.title|safe }}</em></a></p>
    {% endif %}

  </section><!--/chapter -->

  <section class="dig-deeper">
    
    <h2>Dig Deeper</h2>

    <ul class="dig-deeper-list">

      {% for feature in chapter.featured_specials.all %}
        <li>
          <a class="pop_item" href="{% url 'special:'|add:feature.special_type|add:'_detail' feature.slug %}">
          <img src="{{ MEDIA_URL }}special/menupics/{{ feature.slug }}.jpg" alt="image of {{ feature.slug }}">
            {{ feature.title|safe }}
          </a>
        </li>
      {% endfor %}
      
      {% for person in chapter.people.all %}
        <li>
          <a class="pop_item" href="{% url 'supporting:person_detail' person.slug %}">
          <img src="{{ MEDIA_URL }}supporting/person/menupics/{{ person.slug }}.jpg" alt="image of {{ person.slug}}" class="oval">
            {{ person.first_name }} {{ person.middle_name }} {{ person.last_name }}
          </a>
        </li>
      {% endfor %}

      {% for evidenceitem in chapter.evidence.all %}
        <li>
          <a class="pop_item" href="{% url 'supporting:'|add:evidenceitem.evidence_category|add:'_detail' evidenceitem.slug %}">
          <img src="{{ MEDIA_URL }}supporting/evidenceitem/menupics/{{ evidenceitem.slug }}.jpg" alt="image of {{ evidenceitem.slug }}">
            {{ evidenceitem.title|safe }}
          </a>
        </li>
      {% endfor %}
      
      {% for context in chapter.contexts.all %}
        <li>
          <a class="pop_item" href="{% url 'supporting:context_detail' context.slug %}">
          <img src="{{ MEDIA_URL }}supporting/context/menupics/{{ context.slug }}.jpg" alt="image of {{ context.slug }}">
            {{ context.title|safe }}
          </a>
        </li>
      {% endfor %}

    </ul>
  
  </section><!--/dig-deeper -->

   

{% endblock content_area %}

templates/stories/story_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Impressions - Story: {{object.title }} {% endblock %}


{% block wrapper_class %}"content-wrapper--intro"{% endblock wrapper_class %}

{% block content_area %}

  <section class="image-panel">

    <img src="{{ MEDIA_URL }}stories/{{ object.slug }}/{{ object.image_name }}.jpg" alt="story illustration by Monica Vachula">
    <p class="image-panel--caption">
      {{ object.caption|safe }}
      {% if object.source.id != 1 %}
        Image courtesy of {{ object.source.institution|safe }}.
      {% endif %}
    </p>

  </section><!--/image-panel-->

  <article class="text-panel">
    
    <ul class="intro-nav">

      <li class="previous">
        {% if object.get_prev %}
          <a href="{% url 'stories:story_detail' object.get_prev.slug %}">&lArr;&nbsp;Previous <em>{{object.get_prev.title|safe}}</em></a>     
        {% else %}
          <span class="end-of-the-line">&lArr; Previous</span>
        {% endif %}
      </li>

      <li class="read-this">
        <a href="{% url 'stories:chapter_detail' object.slug 1 %}">
          Read This Story
          <img src="{% static 'images/' %}pointing-hand-down.png" alt="pointing hand icon">
        </a>
      </li>

      <li class="next">

        {% if object.get_next %}
          <a href="{% url 'stories:story_detail' object.get_next.slug %}">Next&nbsp;&rArr; <em>{{object.get_next.title|safe}}</em></a>     
        {% else %}
          <span class="end-of-the-line">Next Story &rArr;</span>
        {% endif %}

      </li>

    </ul>

    <h1 class="story-title">{{ object.title|safe }}</h1>
    
    <h2 class="story-subtitle">{{ object.subtitle|safe }}</h2>  

    {{ object.introduction|safe }}

    <p class="story-prompt"><a href="{% url 'stories:chapter_detail' object.slug 1 %}">Read this story&hellip;</a></p>

  </article>



  <!-- Chapter layout has another div here - deeper table-cell -->
{% endblock content_area %}

templates/stories/story_list.html
{% extends "base.html" %}
{% load static %}
{% load media_tags %}

{% block title %}Impressions - Stories{% endblock %}

{% block wrapper_class %}"content-wrapper menus"{% endblock wrapper_class %}

{% block content_area %}

  <h1 class="main-title">Stories</h1>

  <p>These stories tell about the discovery of the dinosaur footprints and about the lives of the discoverers.</p>

  <ul class="menu-gallery three-across">
  {% for object in object_list %}
    <li>
      <a href="{% url 'stories:story_detail' object.slug %}">
        <img src="{% story_image object.slug %}" alt="story illustration">
        <span class="menu-title">{{ object.title|safe }}</span>{{ object.subtitle|safe }}
        {{ object.menu_blurb|safe }}
      </a>
    </li>
  {% endfor %}
  </ul>  


{% endblock content_area %}

templates/stories/team_story_detail.html
{% extends "base_team.html" %}
{% load static %}

{% block content_area %}
	
	<p><a href="{% url 'stories:team_story_list' %}">Return to Story Menu</a></p>

    <h1>{{ object.title|safe }}</h1>
    <h2>Dig Deepers per Chapter</h2>

    <ul>
	{% for chapter in object.chapter_set.all %}
		<li>
			<p>&nbsp;</p>
			<h2>{{ chapter.title|safe}}</h2>

		    <ul>
		      {% for person in chapter.people.all %}
		        <li>
		          Person: <a class="pop_item" href="{% url 'supporting:person_detail' person.slug %}">
		            {{ person.first_name }} {{ person.middle_name }} {{ person.last_name }}
		          </a>
		        </li>
		      {% endfor %}

		      {% for evidenceitem in chapter.evidence.all %}
		        <li>
		          Artifacts &amp; Docs - {{ evidenceitem.evidence_type.slug }}: <a class="pop_item" href="{% url 'supporting:'|add:evidenceitem.evidence_category|add:'_detail' evidenceitem.slug %}">
		            {{ evidenceitem.title|safe }}
		          </a>
		        </li>
		      {% endfor %}
		      
		      {% for context in chapter.contexts.all %}
		        <li>
		          Backdrop: <a class="pop_item" href="{% url 'supporting:context_detail' context.slug %}">
		            {{ context.title|safe }}
		          </a>
		        </li>
		      {% endfor %}

		      {% for special in chapter.featured_specials.all %}
		        <li>
		          Special - {{ special.special_type }}: <a class="pop_item" 
		          href="{% url 'special:'|add:special.special_type|add:'_detail' special.slug %}">
		            {{ special.title|safe }}
		          </a>
		        </li>
		      {% endfor %}
		      
		    </ul>


		</li>
    {% endfor %}
    </ul>



{% endblock content_area %}


    

templates/stories/team_story_list.html
{% extends "base_team.html" %}
{% load static %}

{% block content_area %}
  <p><a href="{% url 'core:team_home' %}">Return to Team Home</a></p>
  <h1>Stories - Dig Deepers per Chapter</h1>
    
  <ul>
  {% for object in object_list %}
    <li>
      <a href="{% url 'stories:team_story_detail' object.slug %}">
        <img src="{% static 'stories/menupics/' %}{{ object.slug }}.jpg">
        <h2>{{ object.title|safe }}</h2>
      </a>
    </li>
  {% endfor %}
  </ul>  


{% endblock content_area %}