config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url('admin/', admin.site.urls),
    path('ancillary/', include('impressions.ancillary.urls', namespace='ancillary')),
    path('', include('impressions.core.urls', namespace='core')),
    path('map/', include('impressions.map.urls', namespace='map')),
    path('special/', include('impressions.special.urls', namespace='special')),
    path('stories/', include('impressions.stories.urls', namespace='stories')),
    path('supporting/', include('impressions.supporting.urls', namespace='supporting')),
    path('themes/', include('impressions.themes.urls', namespace='themes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Also ensure static files are served
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

impressions/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    # a place-holder -- not triggered by js because there is no "mobile menu"
    # to be visible or not
    path('home/intro/page/', views.FullIntroTemplateView.as_view(), name='home_intro'),
    # needed to add third element "page" to match the length of all other urls
    # using full vs. ajax
    path('home/ajax/intro/page/', views.IntroTemplateView.as_view(), name='ajax_home_intro'),
    path('team/', views.TeamHomeTemplateView.as_view(), name='team_home'),
    path('sitemap/', views.SitemapTemplateView.as_view(), name='sitemap'),
]

impressions/map/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="map"

urlpatterns = [
    path('', TemplateView.as_view(template_name="map/map_intro.html"), name='map_intro'),

    path('sites/<slug:slug>/', views.layer_sites, name='site_list'),    
    path('deeper/<slug:slug>/', views.MapDeeperView.as_view(), name='map_deeper'),    
    path('about/<slug:slug>/', views.FullMapAboutView.as_view(), name='about_detail'),    
    path('ajax/about/<slug:slug>/', views.MapAboutView.as_view(), name='ajax_about_detail'),    

    path('', views.MapDetailView.as_view(), name='map_detail'),
    path('detail/', views.MapDetailView.as_view(), name='map_detail'),
]

impressions/special/urls.py
from django.urls import path, re_path
from . import views

app_name="special"

urlpatterns = [
    path('feature/', views.FeatureListView.as_view(), name='feature_list'),

    # CBV approach
    # The first part of each name has to match the corresponding
    # name in special.Feature.special_type, e.g. "video"_detail
    # Applies only to the "staring" names, not subsequent slide details

    # ----------- NON-SLIDE FEATURES ---------

    #  ------ VIDEO ---
    path('video/<slug:slug>/', 
        views.FullVideoDetailView.as_view(), name='video_detail'),

    path('ajax/video/<slug:slug>/', 
        views.VideoDetailView.as_view(), name='ajax_video_detail'),

    path('swapfull/video/<slug:slug>/', 
        views.SwapFullVideoDetailView.as_view(), name='swapfull_video_detail'),

    #  ------ VOICE ---
    # Should have been voice, singular, but too hard to change now
    path('voices/<slug:slug>/', 
        views.FullVoiceDetailView.as_view(), name='voices_detail'),

    path('ajax/voices/<slug:slug>/', 
        views.VoiceDetailView.as_view(), name='ajax_voices_detail'),

    path('swapfull/voices/<slug:slug>/', 
        views.SwapFullVoiceDetailView.as_view(), name='swapfull_voices_detail'),

    #  ------ EXPLORE ---
    path('explore/<slug:slug>/', 
        views.FullExploreDetailView.as_view(), name='explore_detail'),

    path('ajax/explore/<slug:slug>/', 
        views.ExploreDetailView.as_view(), name='ajax_explore_detail'),

    path('swapfull/explore/<slug:slug>/', 
        views.SwapFullExploreDetailView.as_view(), name='swapfull_explore_detail'),

    #  ------ DICOVERERS ---
    # Not stand-alone -- only serves voting in Whose Discovery, Chapter 8
    path('discoverers/<slug:slug>/<slide_num>/', 
        views.DiscoverersDetailView.as_view(), name='discoverers_detail'),

    # ----------- SLIDE-BASED FEATURES ---------

    #  ------ THEN AND NOW ---
    path('then/<slug:slug>/', 
        views.FullThenDetailView.as_view(), name='then_detail'),

    path('ajax/then/<slug:slug>/', 
        views.ThenDetailView.as_view(), name='ajax_then_detail'),

    path('swapfull/then/<slug:slug>/', 
        views.SwapFullThenDetailView.as_view(), name='swapfull_then_detail'),

    #  ------ LOOKING ---
    path('looking/<slug:slug>/', 
        views.FullLookingDetailView.as_view(), name='looking_detail'),

    path('ajax/looking/<slug:slug>/', 
        views.LookingDetailView.as_view(), name='ajax_looking_detail'),

    path('swapfull/looking/<slug:slug>/', 
        views.SwapFullLookingDetailView.as_view(), name='swapfull_looking_detail'),


    #  ------ SLIDESHOW ---
    # Zero param must also go to intro. We're dependent on the link_name 
    # which distinguishes full from slim pop, so we can't just use 
    # slideshow_detail (no int param) for the link in nav
    re_path('slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.IntroSlideshowDetailView.as_view(), name='reintro-slideshow_detail'),

    #  with slide number (other than 0)
    path('slideshow/<slug:slug>/<slide_num>/', 
        views.SlideshowDetailView.as_view(), name='slideshow_slide_detail'),

    # default - full (changed Nov 1, 2017)
    path('slideshow/<slug:slug>/', 
        views.IntroFullSlideshowDetailView.as_view(), name='slideshow_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/slideshow/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='full_slideshow_re_intro_detail'),

    #  full screen with slide number
    path('full/slideshow/<slug:slug>/<slide_num>/', 
        views.FullSlideshowDetailView.as_view(), name='full_slideshow_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/slideshow/<slug:slug>/', 
        views.IntroSlideshowDetailView.as_view(), name='intro_ajax_slideshow_detail'),

    # the moment when you come from a see also on a person full slim
    # re-use ReIntroFullSlideshowDetailView
    path('swapfull/slideshow/<slug:slug>/', 
        views.ReIntroFullSlideshowDetailView.as_view(), name='swapfull_slideshow_detail'),


    #  ------ SOCIETY ---
    # choice for vote
    path('society/choice/<slug:slug>/<slide_num>/<int:choice>)/', 
        views.SocietyChoiceDetailView.as_view(), name='society_choice'),

    # zero version of intro
    re_path('society/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroSocietyDetailView.as_view(), name='society_detail'),

    #  with slide number
    path('society/<slug:slug>/<slide_num>/', 
        views.SocietyDetailView.as_view(), name='society_slide_detail'),

    # default - intro (changed Nov 1, 2017)
    path('society/<slug:slug>/', 
        views.IntroFullSocietyDetailView.as_view(), name='society_detail'),


    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/society/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='full_society_re_intro_detail'),

    #  full screen with slide number
    path('full/society/<slug:slug>/<slide_num>/', 
        views.FullSocietyDetailView.as_view(), name='full_society_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/society/<slug:slug>/', 
        views.IntroSocietyDetailView.as_view(), name='ajax_society_detail'),

    # re-use ReIntroFullSocietyDetailView
    path('swapfull/society/<slug:slug>/', 
        views.ReIntroFullSocietyDetailView.as_view(), name='swapfull_society_detail'),



    #  ------ FOOTPRINTS ---
    # zero version of intro
    re_path('footprint/<slug:slug>/(?P<slide_num>[0])/', 
        views.IntroFootprintDetailView.as_view(), name='footprint_detail'),

    #  with slide number
    path('footprint/<slug:slug>/<slide_num>/', 
        views.FootprintDetailView.as_view(), name='footprint_slide_detail'),

    # default full - intro (changed Nov 1, 2017)
    path('footprint/<slug:slug>/', 
        views.IntroFullFootprintDetailView.as_view(), name='footprint_detail'),

    # zero version of full intro
    # because when we go back to intro, it's via ajax
    re_path('full/footprint/<slug:slug>/(?P<slide_num_arg>[0])/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='full_footprint_re_intro_detail'),


    #  full screen with slide number
    path('full/footprint/<slug:slug>/<slide_num>/', 
        views.FullFootprintDetailView.as_view(), name='full_footprint_slide_detail'),

    # ajax screen default - intro (changed Nov 1, 2017)
    path('ajax/footprint/<slug:slug>/', 
        views.IntroFootprintDetailView.as_view(), name='ajax_footprint_detail'),

    # re-use ReIntroFullFootprinDetailView
    path('swapfull/footprint/<slug:slug>/', 
        views.ReIntroFullFootprintDetailView.as_view(), name='swapfull_footprint_detail'),


    #  ------ TEAM ---
    path('team/feature/', views.TeamFeatureListView.as_view(), \
        name='team_special_list'),

]

impressions/themes/urls.py
from django.urls import path
from . import views

app_name="themes"

urlpatterns = [
    path('', views.ThemeListView.as_view(), name='theme_list'),
    path('<slug:slug>/', views.ThemeDetailView.as_view(), name='theme_detail'),
]

templates/_google_analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-102175578-1', 'auto');
  ga('send', 'pageview');

</script>

templates/base.html
<!DOCTYPE html>
{% load static settings_extras %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="Impressions from a Lost World tells the history of the 19th century discovery of fossilized dinosaur tracks along the Connecticut River Valley in Massachusetts and Connecticut and the profound effect these fossils had upon American science, arts, religion, and culture that reverberates down to the present day.">
  <meta name="keywords" content="fossil, dinosaur, footprints, tracks, history of science, science and religion, Edward Hitchcock, Orra White Hitchcock, James Deane, Dexter Marsh, Benjamin Silliman, history of geology, paleontology, ichnology, New England history, Massachusetts history, Connecticut history, Pocumtuck Valley Memorial Association, Memorial Hall Museum, Deerfield">
  <meta name="google-site-verification" content="hYCaYspmFe4DfmKpxiShMDsTY4eZckSxaF5Mjw_d5dQ" /> 
  
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-3NZRCFG17J"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-3NZRCFG17J');
  </script>

  <title>{% block title %}Impressions From a Lost World{% endblock %}</title>

	{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/application.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/print.css' %}" media="print" type="text/css"/>
    <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic,700' rel='stylesheet' type='text/css'>
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->

  {% endblock stylesheets %}

  {% block javascript %}
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    
    <!-- <script   src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"   integrity="sha256-JklDYODbg0X+8sPiKkcFURb5z7RvlNMIaE3RA2z97vw="   crossorigin="anonymous"></script> -->

    <script type="text/javascript">
      if (typeof jQuery == 'undefined') {
          document.write(unescape("%3Cscript src='{% static 'js/jquery-3.1.1.min.js' %}' type='text/javascript'%3E%3C/script%3E"));
      }
    </script>

<!--     <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 -->    
    <script src="{% static 'js/d3.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/application.js' %}" type="text/javascript"></script>

    <!-- for looking and seeing -->
    <script src="{% static 'js/jquery.jplayer.js' %}" type="text/javascript"></script>

    <!-- for zoom, include only on evidence slim? -->
    <script type="text/javascript" src="{% static 'js/ZoomifyImageViewerPro-min.js' %}"></script>

  {% endblock javascript %}

    <link rel="apple-touch-icon" sizes="57x57" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="60x60" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="https://dinotracksdiscovery.org/static/images/favicon/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="https://dinotracksdiscovery.org/static/images/favicon/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="https://dinotracksdiscovery.org/static/images/favicon/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="https://dinotracksdiscovery.org/static/images/favicon/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="https://dinotracksdiscovery.org/static/images/favicon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="https://dinotracksdiscovery.org/static/images/favicon/favicon-128.png" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/static/images/favicon/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/static/images/favicon/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/static/images/favicon/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/static/images/favicon/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/static/images/favicon/mstile-310x310.png" />

</head>

<body {% block body_class %}{% endblock body_class %}>
{% block full_page %}

<header class="top-navigation">

    <a href="/" class="mobile-logo">
      <img src="{% static 'images/footmark-logo.png' %}" alt="Logo image">
    </a>

    <a href="javascript:void(0)" id="js-top-navigation-mobile-menu" class="top-navigation-mobile-menu">MENU</a>

    <nav>

      <ul id="js-top-navigation-menu" class="top-navigation-menu show">

        <li>
          <img src="{% static 'images/nav-trackways-first.png' %}" alt="footprint icon">
        </li>

        <li>
          <a href="/">Home</a>
          <img src="{% static 'images/nav-trackways-home.png' %}" alt="footprint icon">
        </li>

        <li{% if object.content_type.id == 1 %} class="more"{% endif %}>
          <a href="{% url 'stories:story_list' %}">Stories</a>
          <img src="{% static 'images/nav-trackways-stories.png' %}" alt="footprint icon">
          {% if object.content_type.id == 1 %}
            <ul class="submenu">
              {% for story in object.story_list %}
                <li><a href="{% url 'stories:story_detail' story.slug %}">{{ story.title|safe }}</a></li>
              {% endfor %}
            </ul>
          {% endif %}
        </li>

        <li{% if object.content_type.id == 2 %} class="more"{% endif %}>
          <a href="{% url 'themes:theme_list' %}">Themes</a>
          <img src="{% static 'images/nav-trackways-themes.png' %}" alt="footprint icon">
          {% if object.content_type.id == 2 %}
            <ul class="submenu">
              {% for theme in object.theme_list %}
                <li><a href="{% url 'themes:theme_detail' theme.slug %}">{{ theme.title|safe }}</a></li>
              {% endfor %}
            </ul>
          {% endif %}
        </li>

        <li>
          <a href="{% url 'map:map_intro' %}">Map</a>
          <img src="{% static 'images/nav-trackways-map.png' %}" alt="footprint icon">
        </li>

        <li>
          <ul id="js-2nd-navigation-menu" class="top-navigation-menu secondary-navigation-menu">
            <li><a href="{% url 'supporting:person_list' %}">People</a></li>
            <li><a href="{% url 'supporting:evidenceitem_list' %}">Artifacts &amp; Documents</a></li>
            <li><a href="{% url 'supporting:context_list' %}">Backdrops</a></li>
            <li><a href="{% url 'special:feature_list' %}">Special Features</a></li>
          </ul>
        </li>

      </ul>

    </nav>

</header>

<div class={% block wrapper_class %}"content-wrapper"{% endblock wrapper_class %}>

  {% block content_area %}
    content goes here
  {% endblock content_area %}
  
</div>
{% endblock full_page %}

<footer class="footer">
  <ul class="footer-primary">
    <li><a href="{% url 'ancillary:about' %}">About This Site</a></li>
    <li><a href="{% url 'ancillary:further' %}">For Further Study</a></li>
    <li><a href="{% url 'ancillary:teachers' %}">Teacher Resources</a></li>
    <li><a href="mailto:pvmaoffice@deerfield.history.museum">Contact Us</a></li>
  </ul>
  
  <div class="footer-logos">

    <div class="pvma-logo">
      <a href="https://deerfield-ma.org" target="_blank">
        <img src="{% static 'images/logo-pvma.svg' %}" alt="Pocumtuck Valley Memorial Association logo" width="92" height="93">
      </a>
      <p class="caption"><em>Impressions from a Lost World</em> &copy; 2017 <a href="https://deerfield-ma.org" target="_blank">Pocumtuck Valley Memorial Association</a>, Deerfield, Massachusetts</p>
    </div><!-- /pvma-logo -->

    <div class="award">
      <a href="https://aaslh.org" target="_blank">
        <img src="/static/images/logo-aaslh.jpg" alt="American Association of State and Local History">
      </a>
      <p class="caption">Winner of the 2018 AASLH Award of Merit!</p>
    </div><!-- /award -->
    
  </div><!-- /footer-logos -->

</footer>

{% is_production "" as show_production %}
{% if show_production %}
  {% include "_google_analytics.html" %}
{% endif %}

</body>
</html>

templates/base_error.html
{% extends "base.html" %}
{% load static %}

{% block title %}Impressions From a Lost World - error message{% endblock %}

{% block wrapper_class %}"content-wrapper menus"{% endblock wrapper_class %}

{% block content_area %}

  <header>
    <h1 class="hm-title">Impressions from a Lost World</h1>
  </header>

	<div class="error-msg">
		{% block error_msg %}
			[error msg here]
		{% endblock error_msg %}
	</div>
	
{% endblock content_area %}

templates/base_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object_list.0.content_type.plural_title }}{% endblock %}

{% block title_area %}
  Menu title: 
{% endblock title_area %}


{% block content_area %}

{% block menu %}
	block menu
{% endblock menu %}


{% endblock content_area %}

templates/base_team.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8" />
    <title>{% block title %}Impressions Team site{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/application.css' %}" type="text/css"/>

	<link rel="stylesheet" href="{% static 'css/team_styles.css' %}" type="text/css" />


    <link rel="stylesheet" href="{% static 'css/temp-juliet-supporting.css' %}" type="text/css"/>


    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/temp-4juliet-paging.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/temp-juliet-explore.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/temp-juliet-special.css' %}" type="text/css"/>


    <script src="{% static 'js/application.js' %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static 'js/ZoomifyImageViewerPro-min.js' %}"></script>

</head>

<body>
	
{% block content_area %}
	content goes here
{% endblock content_area %}


</body>
</html>

templates/intro.html
{% load static %}


<div id="slimpop-wrapper">
  <div class="slim-border">
    <p class="slimpop-close"><a href='javascript:hideBox();'>close</a></p>

        {% include "_intro.html" %}


  </div><!--slim-border -->
</div><!--slimpop-wrapper -->

templates/sitemap.html
{% extends "base.html" %}
{% load static %}

{% block title %}Impressions from a Lost World{% endblock %}

{% block body_class %}class="home"{% endblock body_class %}

{% block full_page %}

  <div class="content-wrapper">

    <header>
      <h1 class="hm-title"><a href="/">Impressions from a Lost World</a></h1>
      <p class="hm-subtitle">Site Map</p>
    </header>

    <div class="hm-col-1">

      <a href="/supporting/context/" class="hm-menu-item">
        <h2 class="hm-menu-link">Backdrops</h2>
      </a>
       <ul>
          {% for backdrop in backdrops %}
            <li> - <a href="{% url 'supporting:context_detail' backdrop.slug %}">{{ backdrop.title }}</a></li>
          {% endfor %}
      </ul>

     <a href="/special/feature/" class="hm-menu-item">
        <h2 class="hm-menu-link">Special Features</h2>
      </a>

      <p>Then and Now</p>
      <ul>
      {% for then in features.0.then_list %}
        <li>
          <a href="{% url 'special:then_detail' then.slug %}">
           {{ then.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>

      <p>Slideshows</p>
      <ul>
      {% for slideshow in features.0.slideshow_list %}
        <li>
          <a href="{% url 'special:slideshow_detail' slideshow.slug %}">
           {{ slideshow.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>

      <p>Videos</p>
      <ul>
      {% for video in features.0.video_list %}
        <li>
          <a href="{% url 'special:video_detail' video.slug %}">
           {{ video.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>

      <p>Activities</p>
      {# one at a time for these, no loop #}
      <ul>
        <li>
          <a href="{% url 'special:footprint_detail' 'find-footprints' %}">
           Find the Footprints
          </a>
        </li>
        <li>
          <a href="{% url 'special:explore_detail' 'jurassic-landscape' %}">
           Late Triassic Landscape
          </a>
        </li>
        <li>
          <a href="{% url 'special:society_detail' 'society-quiz' %}">
           "Topics Under Consideration" Quiz
          </a>
        </li>
      </ul>

      <p>Voices</p>
      <ul>
      {% for voices in features.0.voices_list %}
        <li>
          <a href="{% url 'special:voices_detail' voices.slug %}">
           {{ voices.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>

      <p>Looking &amp; Seeing</p>
      <ul>
      {% for looking in features.0.looking_list %}
        <li>
          <a href="{% url 'special:looking_detail' looking.slug %}">
           {{ looking.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>


      <a href="/stories/" class="hm-menu-item">
        <h2 class="hm-menu-link">Stories</h2>
      </a>
      <ul>
      {% for object in stories %}
        <li>
          <a href="{% url 'stories:story_detail' object.slug %}" target="from-map">
            {{ object.title|safe }}
          </a>
        </li>
      {% endfor %}
      </ul>  

      <a href="/themes/" class="hm-menu-item">
        <h2 class="hm-menu-link">Themes</h2>
      </a>
          <ul>
            <li>Theme 1</li>
            <li>Theme 2</li>
            <li>Theme 3</li>
          </ul>


    </div><!-- /hm-col-1 -->

    <div class="hm-col-2">

      <a href="/map/" class="hm-menu-item">
        <h2 class="hm-menu-link">Map</h2>
      </a>
      <a href="/supporting/person/" class="hm-menu-item" target="from-map">
        <h2 class="hm-menu-link">People</h2>
      </a>
        <ul>
          <li>Primary
            <ul>
              {% for person in prime_peeps %}
                <li> - <a href="{% url 'supporting:person_detail' person.slug %}">{{ person.title }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li>Secondary
            <ul>
              {% for person in second_peeps %}
                <li> - <a href="{% url 'supporting:person_detail' person.slug %}">{{ person.last_name }}, {{ person.first_name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li>Minor
            <ul>
              {% for person in minor_peeps %}
                <li> - <a href="{% url 'supporting:person_detail' person.slug %}">{{ person.last_name }}, {{ person.first_name }}</a></li>
              {% endfor %}
            </ul>
          </li>
        </ul>

    </div><!-- /hm-col-2 -->

    <div class="hm-col-3">

      <a href="/supporting/evidenceitem/" class="hm-menu-item">
        <h2 class="hm-menu-link">Artifacts &amp; Documents</h2>
      </a>
          
      <ul>
          {% for evidenceitem in evidenceitems %}
            <li> - <a href="{% url 'supporting:'|add:evidenceitem.evidence_category|add:'_detail' evidenceitem.slug %}">
            {{ evidenceitem.title }}</a></li>
          {% endfor %}
      </ul>
 
    </div><!-- /hm-col-3 -->

  </div><!--/content-wrapper -->

{% endblock full_page %}

templates/team_index.html
{% extends "base_team.html" %}
{% load static %}

{% block content_area %}

<h1 class="story-title">Impressions Team Lists</h1>
    
<h3><a href="{% url 'stories:team_story_list' %}">Stories  -- Dig Deepers per Chapter</a></h3>

<h3><a href="{% url 'supporting:team_type_list' %}">Supporting Items -- where they appear</a></h3>


{% endblock content_area %}